### PR TITLE
Update pvol_us.Rmd

### PR DESCRIPTION
**Pull request by CeciliaNilsson709**
@adokter can you please review and add information?

### CODE REVIEW

**Comment by adokter** [comment]
@peterdesmet can you add me as a collaborator to this repo, it wants me to create a fork if I want to edit anything. Or is there a different way to avoid that?

**Comment by peterdesmet** [comment]
I've made you maintainer, but @CeciliaNilsson709 should allow "edit to maintainers" on her branch first. @CeciliaNilsson709 [here](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork)'s how you can do that.

@adokter that way, you should be able to continue working on [`CeciliaNilsson709:patch-2`](https://github.com/CeciliaNilsson709/globam-dmp/tree/patch-2)

Let me know if this doesn't work.

**Comment by CeciliaNilsson709** [comment]
Edits are already allowed, so should work now I guess?

**Comment by peterdesmet** [comment]
@adokter looks like the last commit caused the Travis build to fail (see the ❌). Will have to figure out why (maybe the added jpg) + add a check that pull requests cannot be merged before passing.

Also, I’ll add the two of you as co-authors in the citation of the DMP.👌

**Comment by adokter** [comment]
whoops hitting the merge button to quickly apparently...

**Pull request merged**
